codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        target: auto
        threshold: 5%
        informational: false
    patch:
      default:
        target: auto
        threshold: 10%
        informational: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff, flags, components, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/**/*"
  - "scripts/**/*"
  - "**/*.d.ts"
  - "src/background/**/*"
  - "src/popup/**/*"
  - "src/options/**/*"
  - "src/content/display.ts"
